apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: y-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /home
            pathType: Prefix
            backend:
              service:
                name: y-app
                port:
                  name: http