apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: y-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: cxp.k8s.azure.msgoat.eu
      http:
        paths:
          - path: /cxp-team-y/y-app(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: y-app-service
                port:
                  name: http